---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: food2gether
  labels:
    app: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  auth-service
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: docker.io/kicbase/echo-server:1.0 # ghcr.io/food2gether/auth-service:0.0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env: []
        ports:
        - containerPort: 8080
          name: auth-service
      restartPolicy: Always
